version: 2.1
orbs:
  node: circleci/node@1.1

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: |
          yarn install
          yarn run build --prod
      - run: |
          curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
          unzip awscli-bundle.zip
          ./awscli-bundle/install -b ~/bin/aws
      - run: |
          PUBLIC_IP=$(curl ipinfo.io/ip)
          AWS_REGION=ap-northeast-2
      - run: |
          scp -r ./build/* ec2-user@ec2-13-209-65-219.ap-northeast-2.compute.amazonaws.com:/usr/share/nginx/html/
